name: Deploy pandawarden to hetzner
on: push
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Setup backend
        working-directory: ./backend
        run: |
          mkdir -p public
          cp -r ../frontend/dist/* public/
          npm ci

      - name: Setup scrapers
        working-directory: ./scrapers
        run: |
          npm ci
          npm run playwright-init
          
      - name: Setup backend and scraper environments
        run: |
          echo "${{ secrets.BACKEND_ENV_FILE }}" >> ./backend/.env
          echo "${{ secrets.SCRAPERS_ENV_FILE }}" >> ./scrapers/.env
      
      - name: Deploy to hetzner
        run: |
          rsync -azP \
            -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" \
            ./ \
            ${{ secrets.ARTIFACT_USERNAME }}@${{ secrets.ARTIFACT_HOST }}:~/PandaWarden/
        
      - name: Restart PM2 processes
        run: |
          ssh -i $HOME/.ssh/id_ed25519 ${{ secrets.ARTIFACT_USERNAME }}@${{ secrets.ARTIFACT_HOST }} \
            'cd ~/PandaWarden && pm2 restart all'